# Generated by Django 5.1.7 on 2025-03-29 20:07

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
